### ISSUE TITLE
Bugs report

### ISSUE THREAD

**Issue by ruozhoulin** [NKrvavica/LineProbes#1]
Dear developer, thank you so much for sharing this script! It really saves me a lot of time.

However, I find some bugs in this script, and I can help you fix them and make the documentation more detailed by pulling my branch.

One bug is that `asscalar` is not supported by `numpy` anymore. Besides, the script raises errors in special cases, e.g., when no water exist or is full of water at some moment.

**Comment by NKrvavica** [comment]
Thanks for the information. Unfortunately, I have not used the script for a long time, so it is possible that there are some deprecations. If you would like to fix it and improve the documentation, feel free to make a pull request and do the modification.

**Comment by ruozhoulin** [comment]
Hi, I am happy to improve this amazing repository! I think it is the only place that helps people monitor water depth in OpenFOAM on the entire Internet.

However, I failed to pull my request because I am not a **collaborator** yet. So could you please add me as a collaborator of this repository? [Here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository) is how to invite collaborators.

**Comment by NKrvavica** [comment]
No problem, I have added you as a collaborator, let me know if you have access now.

**Comment by ruozhoulin** [comment]
Hi, I am a collaborator now thanks to your help. I have submitted my pull request. Please check it and modify anywhere inappropriate as you wish.

**Comment by NKrvavica** [comment]
Thank you, everything looks good.
